#
###################################
# Site wide configuration
####################################
#
title:       "码农小霍2017-07"
description: "域名到期时间2017-07"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:        Asia/Beijing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 码农小霍
  avatar: avatar.jpg
  job: "iOS Coder"
  bio: "博观而约取，厚积而薄发"
  email: 349574068@qq.com
  disqus-shortname:
  twitter:
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: HuoYongJie
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  soundcloud: #username
  flickr: #username
  codepen: #username
